name: pocket-js-server

services:
  pg:
    image: postgres:17.4
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
